version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: scan_cv_backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/scan_cv
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
  pgadmin:
    image: dpage/pgadmin4
    container_name: scan_cv_pgadmin
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - app-network
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: scan_cv_frontend
    restart: unless-stopped
    environment:
      - API_URL=http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: scan_cv_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scan_cv
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: